# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class CompareChanges < Formula
  desc 'WIP'
  homepage 'http://anttiharju.dev/compare-changes'
  version '0.1.1'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url 'https://github.com/anttiharju/compare-changes/releases/download/v0.1.1/compare-changes-darwin-arm64.tar.gz'
      sha256 '58605a3efe2d02ccf707db42c85a6b9af6408741b744bca69c0636072e5ad82c'

      def install
        bin.install 'compare-changes'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/compare-changes/releases/download/v0.1.1/compare-changes-linux-amd64.tar.gz'
      sha256 '07e1fe9d6ac8d6d89ea2a479a9de95283642d1f5d34bd2e487edf12ec13c001d'

      def install
        bin.install 'compare-changes'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/compare-changes/releases/download/v0.1.1/compare-changes-linux-arm64.tar.gz'
      sha256 '305438ab9aef410ce5d18af011072846b700ef8aa206265750c44e5a2e502e93'

      def install
        bin.install 'compare-changes'
      end
    end
  end

  test do
    system "#{bin}/compare-changes version"
  end
end
