# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class CompareChanges < Formula
  desc 'WIP'
  homepage 'http://anttiharju.dev/compare-changes/'
  version '0.1.2'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url 'https://github.com/anttiharju/compare-changes/releases/download/v0.1.2/compare-changes-darwin-arm64.tar.gz'
      sha256 'f07871e2c283f4ea11be22afcf5f6a201fef38df1c22482f7991e787210b27c1'

      def install
        bin.install 'compare-changes'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/compare-changes/releases/download/v0.1.2/compare-changes-linux-amd64.tar.gz'
      sha256 'a002f36d6e91564c038b4598fe980c10095a272764d02be65b08187c0367cc5f'

      def install
        bin.install 'compare-changes'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/compare-changes/releases/download/v0.1.2/compare-changes-linux-arm64.tar.gz'
      sha256 '6a5b761969e64956cd87ea1d5e654c83d160a9c325b48f1cdbb4194e6e010010'

      def install
        bin.install 'compare-changes'
      end
    end
  end

  test do
    system "#{bin}/compare-changes"
  end
end
