# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class CompareChanges < Formula
  desc 'For use with find-changes-action'
  homepage 'http://anttiharju.dev/compare-changes/'
  version '0.8.1'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/anttiharju/compare-changes/releases/download/v#{version}/compare-changes-aarch64-apple-darwin.tar.gz"
      sha256 'eaf13fabad773879f645e9582d18ba5eddc50b815382b289abcafe69399664cb'

      def install
        bin.install 'compare-changes'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anttiharju/compare-changes/releases/download/v#{version}/compare-changes-aarch64-unknown-linux-musl.tar.gz"
      sha256 'b55578a23b6912655e783c7e8354d8924fea3157d7284d2333f8aeffce17aab9'

      def install
        bin.install 'compare-changes'
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anttiharju/compare-changes/releases/download/v#{version}/compare-changes-x86_64-unknown-linux-musl.tar.gz"
      sha256 '2c4fae2021d54cab9349e5a1cf23824c82039c97d9ea4bb9c182de90a0c9556e'

      def install
        bin.install 'compare-changes'
      end
    end
  end

  test do
    system "#{bin}/compare-changes --version"
  end
end
