# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class CompareChanges < Formula
  desc 'WIP'
  homepage 'http://anttiharju.dev/compare-changes/'
  version '0.1.3'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url 'https://github.com/anttiharju/compare-changes/releases/download/v0.1.3/compare-changes-aarch64-apple-darwin.tar.gz'
      sha256 'edf047bf0b3bd10c39222fdc0bf0753d98648d51a82bbe1fa2644ac04069389b'

      def install
        bin.install 'compare-changes'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/compare-changes/releases/download/v0.1.3/compare-changes-x86_64-unknown-linux-gnu.tar.gz'
      sha256 'f02a035bebf8ec3f1cb170c952ccf5c236d7aff3d2233374c656c45c59b84441'

      def install
        bin.install 'compare-changes'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/compare-changes/releases/download/v0.1.3/compare-changes-aarch64-unknown-linux-gnu.tar.gz'
      sha256 '173d022b4bff7e9751a6d5cc53ddff0bb9228eaf500486f3cb9cc2936988c0fa'

      def install
        bin.install 'compare-changes'
      end
    end
  end

  test do
    system "#{bin}/compare-changes"
  end
end
