# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class Relcheck < Formula
  desc 'Performant relative link checker'
  homepage 'https://anttiharju.dev/relcheck'
  version '1.8.18'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/anttiharju/relcheck/releases/download/v#{version}/relcheck-darwin-arm64.tar.gz"
      sha256 '30ad97dd764242c3f9f3240a9aa1028aca223c65e7d59b94c143356ee679e8ad'

      def install
        bin.install 'relcheck'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anttiharju/relcheck/releases/download/v#{version}/relcheck-linux-arm64.tar.gz"
      sha256 '3ace611b55c51c28381d3ad9d98728862eec8d8aa1852096a3251f5937650368'

      def install
        bin.install 'relcheck'
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anttiharju/relcheck/releases/download/v#{version}/relcheck-linux-amd64.tar.gz"
      sha256 '37b0a056b587036fd814d478c7b0a73e0cb134c8c563ae52aa79b7b7616e0103'

      def install
        bin.install 'relcheck'
      end
    end
  end

  test do
    system "#{bin}/relcheck --version"
  end
end
