# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class Relcheck < Formula
  desc 'Performant relative link checker'
  homepage 'https://anttiharju.dev/relcheck'
  version '1.8.14'
  license 'MIT'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/anttiharju/relcheck/releases/download/v1.8.14/relcheck-darwin-amd64.tar.gz'
      sha256 'fea9c44884152524f8a6e64e6a3c95ae45c4f0a0ac37921f5b6a35f3012e8311'

      def install
        bin.install 'relcheck'
      end
    end
    if Hardware::CPU.arm?
      url 'https://github.com/anttiharju/relcheck/releases/download/v1.8.14/relcheck-darwin-arm64.tar.gz'
      sha256 '502bdf907aa99db4c1bfc3d59ed7b9a7e181e4a25b5c8490adfdbdf146ec0794'

      def install
        bin.install 'relcheck'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/relcheck/releases/download/v1.8.14/relcheck-linux-arm64.tar.gz'
      sha256 '176792fe9209d5aa954224ad6bfc4ec1963feea79bbac3d149ec46635d76e911'

      def install
        bin.install 'relcheck'
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/relcheck/releases/download/v1.8.14/relcheck-linux-amd64.tar.gz'
      sha256 '331cfcf8b559f70654b29bdb07c23d1453b061fedfee25dec2370a6022eec92f'

      def install
        bin.install 'relcheck'
      end
    end
  end

  test do
    system "#{bin}/relcheck version"
  end
end
