# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class Slack9 < Formula
  desc '🐵 Slack TUI to Track Your Mentions In Style!'
  homepage 'https://anttiharju.dev/slack9'
  version '0.5.8'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/anttiharju/slack9/releases/download/v#{version}/slack9-aarch64-apple-darwin.tar.gz"
      sha256 'a20be442ad174217135be7214b4e739421c8c35a76d2de23071f20df7f526069'

      def install
        bin.install 'slack9'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anttiharju/slack9/releases/download/v#{version}/slack9-aarch64-unknown-linux-musl.tar.gz"
      sha256 '49af1315d9b42824e28a25bb6a2095b35fa2ba61cff14218a645ccac812f81b5'

      def install
        bin.install 'slack9'
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anttiharju/slack9/releases/download/v#{version}/slack9-x86_64-unknown-linux-musl.tar.gz"
      sha256 '617e362a699e58c367f433365034593715e08ca2567eb0e512dc19404333b276'

      def install
        bin.install 'slack9'
      end
    end
  end

  test do
    system "#{bin}/slack9 --version"
  end
end
