# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class Slack9 < Formula
  desc '🐵 Slack TUI to Track Your Mentions In Style!'
  homepage 'http://anttiharju.dev/slack9'
  version '0.4.5'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/anttiharju/slack9/releases/download/v#{version}/slack9-aarch64-apple-darwin.tar.gz"
      sha256 '4678f3e7fd76b7946acab5e6940757c19beb41e48300da59a500da1607013173'

      def install
        bin.install 'slack9'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anttiharju/slack9/releases/download/v#{version}/slack9-aarch64-unknown-linux-musl.tar.gz"
      sha256 '964dbddab703ab10033489b5af62dd674ecd1d510c3648d2d92f70aa17ad3053'

      def install
        bin.install 'slack9'
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anttiharju/slack9/releases/download/v#{version}/slack9-x86_64-unknown-linux-musl.tar.gz"
      sha256 'daef75f468e85e9a251a563fbec0f9198abdaef8a296bf2926da77564d78b9e5'

      def install
        bin.install 'slack9'
      end
    end
  end

  test do
    system "#{bin}/slack9 --version"
  end
end
