# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class Slack9 < Formula
  desc 'Enter cloud nine'
  homepage 'https://anttiharju.dev/slack9'
  version '0.2.1'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/anttiharju/slack9/releases/download/v#{version}/slack9-aarch64-apple-darwin.tar.gz"
      sha256 '566d8e55c3765a2a7d5c543d7cb91c10b10ed252534f45001943b560ef0f8303'

      def install
        bin.install 'slack9'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anttiharju/slack9/releases/download/v#{version}/slack9-aarch64-unknown-linux-musl.tar.gz"
      sha256 '601fb467e65b0e484bb358d33d985012668d1e03e431374782167d0e9723467e'

      def install
        bin.install 'slack9'
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anttiharju/slack9/releases/download/v#{version}/slack9-x86_64-unknown-linux-musl.tar.gz"
      sha256 '77a750a18f5d86ce5e9572d64e10641fd5fa42edd92db032d0553e53b9a75752'

      def install
        bin.install 'slack9'
      end
    end
  end

  test do
    system "#{bin}/slack9 --version"
  end
end
