# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class Vmatch < Formula
  desc 'Go and golangci-lint automation'
  homepage 'https://anttiharju.dev/vmatch'
  version '1.0.55'
  license 'MIT'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/anttiharju/vmatch/releases/download/v1.0.55/vmatch-darwin-amd64.tar.gz'
      sha256 'c7660e555cca7c116e49204262a24106596d2946d0f848173728d6c3da47a279'

      def install
        bin.install 'vmatch'
      end
    end
    if Hardware::CPU.arm?
      url 'https://github.com/anttiharju/vmatch/releases/download/v1.0.55/vmatch-darwin-arm64.tar.gz'
      sha256 'b7de697eab35672e0e55dcb6cff00cb62bfabf1ef5e684a9034fdea1937b549b'

      def install
        bin.install 'vmatch'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/vmatch/releases/download/v1.0.55/vmatch-linux-arm64.tar.gz'
      sha256 'f74a9144e4ed49954b15d29bda9557dc054f082cb792c1d2c4bb864b23ea5ab2'

      def install
        bin.install 'vmatch'
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/vmatch/releases/download/v1.0.55/vmatch-linux-amd64.tar.gz'
      sha256 '2e7070addfb86995b854bf52a7a5675d8add1147aa030823907107d7a9510d8f'

      def install
        bin.install 'vmatch'
      end
    end
  end

  test do
    system "#{bin}/vmatch version"
  end
end
