# frozen_string_literal: true

# This file is generated by render.bash, do not edit manually.
class Vmatch < Formula
  desc 'Go & golangci-lint version automation'
  homepage 'https://anttiharju.dev/vmatch'
  version '1.0.3'
  license 'MIT'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/anttiharju/vmatch/releases/download/v1.0.3/vmatch-darwin-amd64.tar.gz'
      sha256 '28c5613018ab90ec4f89cc56670ec44e9038008eaa34dc482a5912b1fafa9d02'

      def install
        bin.install 'vmatch'
      end
    end
    if Hardware::CPU.arm?
      url 'https://github.com/anttiharju/vmatch/releases/download/v1.0.3/vmatch-darwin-arm64.tar.gz'
      sha256 'b836d907247a09abc3ed02fca4bc688835c3f342cc1bbc314faed57e1f4e592c'

      def install
        bin.install 'vmatch'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/vmatch/releases/download/v1.0.3/vmatch-linux-amd64.tar.gz'
      sha256 'ab25c9eb49d3a52bf55b5cb9c3b8e3c73e6893e9772942aec49df7c085f9e5e0'

      def install
        bin.install 'vmatch'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/anttiharju/vmatch/releases/download/v1.0.3/vmatch-linux-arm64.tar.gz'
      sha256 '18836d47b818abdb41376a67cc99c27f7aefe29214c842a180022b923955fca7'

      def install
        bin.install 'vmatch'
      end
    end
  end

  test do
    system "#{bin}/vmatch version"
  end
end
