name: Homebrew Formula

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
      description:
        required: true
        type: string
      homepage:
        required: true
        type: string
      url:
        required: true
        type: string
      go:
        required: true
        type: string

permissions:
  contents: write

jobs:
  render:
    name: Render
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render Formula
        env:
          NAME: ${{ inputs.name }}
          DESCRIPTION: ${{ inputs.description }}
          HOMEPAGE: ${{ inputs.homepage }}
          URL: ${{ inputs.url }}
          GO: ${{ inputs.go }}
        run: scripts/render.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # github-actions[bot]@users.noreply.github.com

          if [ -z "$(git status --porcelain)" ]; then
            echo "Formula $name is already up to date!"
          else
            git add Formula/"$name".rb
            GIT_COMMITTER_NAME="$actor" GIT_COMMITTER_EMAIL="$actor@users.noreply.github.com" git commit -m "Update $name formula"
            git push
          fi
        env:
          actor: ${{ github.actor }}
          name: ${{ inputs.name }}
