name: Homebrew Formula

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
      description:
        required: true
        type: string
      homepage:
        required: true
        type: string
      url:
        required: true
        type: string
      go:
        required: true
        type: string

permissions:
  contents: write

jobs:
  render:
    name: Render
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render Formula
        env:
          NAME: ${{ inputs.name }}
          DESCRIPTION: ${{ inputs.description }}
          HOMEPAGE: ${{ inputs.homepage }}
          URL: ${{ inputs.url }}
          GO: ${{ inputs.go }}
        run: scripts/render.py

      - name: Extract version from url
        id: extract-version
        run: |
          echo "version=$(echo ${{ inputs.url }} | sed -E 's/.*\/([^\/]+)\.tar\.gz/\1/')" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: anttiharju/actions/commit-changes@v0
        with:
          message: "Update ${{ inputs.name }} to ${{ steps.extract-version.outputs.version }}"
